In [1]:
import math 

In [2]:
def fact(n):
    if n == 1:
        return 1
    else: 
        return (n*fact(n-1))

In [3]:
from math import pi

In [4]:
from math import e
from math import sqrt

In [5]:
def stirfac(n):
    if n == 1:
        return 1
    else:
        return (((n/e)**n)*sqrt(2*pi*n))

In [6]:
def EA(n):
    return abs(fact(n)-stirfac(n))

In [7]:
def ER(n):
    return EA(n)/fact(n)

In [8]:
EA(5)

1.9808320424099009

In [9]:
ER(10)

0.008295960443938127

In [10]:
#El error absoluto crece mientras que el error relativo decrece.

In [11]:
#EJERCICIO 2

In [12]:
import math

def func_e(x, n):
    e_approx = 0
    for i in range(n):
        e_approx += x**i/math.factorial(i)
    return e_approx

In [13]:
a = [func_e(1,20),   math.e]
b = [func_e(-1,20),  math.e**-1]
c = [func_e(5,20),   math.e**5]
d = [func_e(-5,20),  math.e**-5]
e = [func_e(10,20),  math.e**10]
f = [func_e(-10,20), math.e**-10]
g = [func_e(15,20),  math.e**15]
h = [func_e(-15,20), math.e**-15]
j = [func_e(20,20),  math.e**20]
i = [func_e(-20,20), math.e**-20]

In [14]:
list = [a, b, c, d, e, f, g, h, j, i]
for i in list:
    print(i)

[2.7182818284590455, 2.718281828459045]
[0.36787944117144245, 0.36787944117144233]
[148.4131078683383, 148.41315910257657]
[0.00670634105421557, 0.006737946999085469]
[21950.37884943194, 22026.465794806703]
[-27.70631023742594, 4.5399929762484875e-05]
[2861105.4127726085, 3269017.372472108]
[-79065.78013803897, 3.0590232050182605e-07]
[228152458.75893375, 485165195.40978974]
[-21822593.77927747, 2.06115362243856e-09]


In [15]:
#Ejercicio 3

In [16]:
a = 2.0
while a<a**2:
    a=a**2
    print(a)

4.0
16.0
256.0
65536.0
4294967296.0
1.8446744073709552e+19
3.402823669209385e+38
1.157920892373162e+77
1.3407807929942597e+154


OverflowError: (34, 'Result too large')

In [17]:
# En aritmetica real nunca se cumple porque siempre se tiene que x(n) < x(n+1), 
#El ciclo realizo 9 iteraciones
# Estos fueron el penultimo y ultimo valor de la variable: 1.157920892373162e+77, 1.3407807929942597e+154; respectivamente.

In [18]:
#Ejercicio 4

In [19]:
import numpy as np
import sys

n = int(input('introduce matriz de orden: '))

a = np.zeros((n,2*n))


print('ingresa los valores de la matriz:')
for i in range(n):
    for j in range(n):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

for i in range(n):        
    for j in range(n):
        if i == j:
            a[i][j+n] = 1

for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('no se puede divir entre cero!')
        
    for j in range(n):
        if i != j:
            radio = a[j][i]/a[i][i]

            for k in range(2*n):
                a[j][k] = a[j][k] - radio * a[i][k]


for i in range(n):
    divisor = a[i][i]
    for j in range(2*n):
        a[i][j] = a[i][j]/divisor


print('\nINVERSA DE LA MARTRIZ ES:')
for i in range(n):
    for j in range(n, 2*n):
        print(a[i][j], end='\t')
    print()

introduce matriz de orden: 0
ingresa los valores de la matriz:

INVERSA DE LA MARTRIZ ES:


In [20]:
#Norma infinito

In [34]:
import numpy as np
from numpy import linalg as LA


#hacemos un array
B= np.array([[-2,1,1],[-2,-5,1],[1,0,2]])
A= np.array([[1.0125, 2,3],[1,2,3],[0,0,1]])
IA = np.array([[80, -80,-8.772132],[-40, 40.5,-1.4999],[0,0,1]])
IB= np.array([[-0.3333,-0.6666,0.2],[0.1666,-0.1666,0],[0.166666,0.03333,0.4]])
print("nuestros arrays:\n",A)
print("                      ")
print(B)
print("                      ")
print(IA)
print("                      ")
print(IB)
print("                      ")

print(abs(A[0,[0]])+abs(A[0,[1]])+abs(A[0,[2]]))
print(abs(A[1,[0]])+abs(A[1,[1]])+abs(A[1,[2]]))
print(abs(A[2,[0]])+abs(A[2,[1]])+abs(A[2,[2]]))

print("            ")

print(abs(B[0,[0]])+abs(B[0,[1]])+abs(B[0,[2]]))
print(abs(B[1,[0]])+abs(B[1,[1]])+abs(B[1,[2]]))
print(abs(B[2,[0]])+abs(B[2,[1]])+abs(B[2,[2]]))

print("          ")
print(abs(IA[0,[0]])+abs(IA[0,[1]])+abs(IA[0,[2]]))
print(abs(IA[1,[0]])+abs(IA[1,[1]])+abs(IA[1,[2]]))
print(abs(IA[2,[0]])+abs(IA[2,[1]])+abs(IA[2,[2]]))
print("            ")
print(abs(IB[0,[0]])+abs(IB[0,[1]])+abs(IB[0,[2]]))
print(abs(IB[1,[0]])+abs(IB[1,[1]])+abs(IB[1,[2]]))
print(abs(IB[2,[0]])+abs(IB[2,[1]])+abs(IB[2,[2]]))

nuestros arrays:
 [[1.0125 2.     3.    ]
 [1.     2.     3.    ]
 [0.     0.     1.    ]]
                      
[[-2  1  1]
 [-2 -5  1]
 [ 1  0  2]]
                      
[[ 80.       -80.        -8.772132]
 [-40.        40.5       -1.4999  ]
 [  0.         0.         1.      ]]
                      
[[-0.3333   -0.6666    0.2     ]
 [ 0.1666   -0.1666    0.      ]
 [ 0.166666  0.03333   0.4     ]]
                      
[6.0125]
[6.]
[1.]
            
[4]
[8]
[3]
          
[168.772132]
[81.9999]
[1.]
            
[1.1999]
[0.3332]
[0.599996]


In [22]:
condA = 6.0125*168.772132
condB = 8*1.1999
print(condA)
print(condB)

1014.74244365
9.5992


In [23]:
#ejercicio 5

In [24]:
#matriz de hilbert
def hibert(a,b):
    li=[[]]*a
    for i in range(a):
        for j in range(b):
            ele=math.pow((i+j+1),-1)
            li[i].append(ele)
    return li

In [26]:
hibert(3,3)

[[1.0,
  0.5,
  0.3333333333333333,
  0.5,
  0.3333333333333333,
  0.25,
  0.3333333333333333,
  0.25,
  0.2],
 [1.0,
  0.5,
  0.3333333333333333,
  0.5,
  0.3333333333333333,
  0.25,
  0.3333333333333333,
  0.25,
  0.2],
 [1.0,
  0.5,
  0.3333333333333333,
  0.5,
  0.3333333333333333,
  0.25,
  0.3333333333333333,
  0.25,
  0.2]]

In [27]:
def Hilb(a, b):
    return [[1 / (i + j + 1) for j in range(b)] for i in range(a)]

In [28]:
Hilb(3,3)

[[1.0, 0.5, 0.3333333333333333],
 [0.5, 0.3333333333333333, 0.25],
 [0.3333333333333333, 0.25, 0.2]]

In [42]:
for i in range(30):
    print(Hilb(i,i))

[]
[[1.0]]
[[1.0, 0.5], [0.5, 0.3333333333333333]]
[[1.0, 0.5, 0.3333333333333333], [0.5, 0.3333333333333333, 0.25], [0.3333333333333333, 0.25, 0.2]]
[[1.0, 0.5, 0.3333333333333333, 0.25], [0.5, 0.3333333333333333, 0.25, 0.2], [0.3333333333333333, 0.25, 0.2, 0.16666666666666666], [0.25, 0.2, 0.16666666666666666, 0.14285714285714285]]
[[1.0, 0.5, 0.3333333333333333, 0.25, 0.2], [0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666], [0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285], [0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125], [0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111]]
[[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666], [0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285], [0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125], [0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111], [0.2, 0.16666666666666666, 0.1428571428

In [49]:
import numpy as np
for i in range(30):
    print(np.linalg.inv(Hilb(i+1,i+1))) #se sumo i+1 porque de lo contrario python decía que para Hilb(1,1) la dimension debía ser mayor a 2

[[1.]]
[[ 4. -6.]
 [-6. 12.]]
[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]
[[ 3.60000e+01 -6.30000e+02  3.36000e+03 -7.56000e+03  7.56000e+03
  -2.77200e+03]
 [-6.30000e+02  1.47000e+04 -8.82000e+04  2.11680e+05 -2.20500e+05
   8.31600e+04]
 [ 3.36000e+03 -8.82000e+04  5.64480e+05 -1.41120e+06  1.51200e+06
  -5.82120e+05]
 [-7.56000e+03  2.11680e+05 -1.41120e+06  3.62880e+06 -3.96900e+06
   1.55232e+06]
 [ 7.56000e+03 -2.20500e+05  1.51200e+06 -3.96900e+06  4.41000e+06
  -1.74636e+06]
 [-2.77200e+03  8.31600e+04 -5.82120e+05  1.55232e+06 -1.74636e+06
   6.985

In [60]:
for i in range(15):
    print(np.linalg.det(Hilb(i+1,i+1))*np.linalg.det(np.linalg.inv(Hilb(i+1,i+1))))

1.0
1.0000000000000004
0.9999999999999999
0.9999999999999875
1.000000000000103
0.9999999999936762
0.9999999998822416
1.0000000181706385
1.0000008513805414
1.000011609147632
1.0000137665630577
0.9993656650056082
0.879720039045851
1.5983961044623172
1.19829787834176


In [61]:
#Notemos que conforme n crece, el detHxdetH^-1 se van alejando del 1.0

In [45]:
#ejercicio 6
import math
MAX = 100
 
def Cholesky(matrix, n):
 
    lower = [[0 for x in range(n + 1)]
                for y in range(n + 1)]

    for i in range(n):
        for j in range(i + 1):
            sum1 = 0
 

            if (j == i):
                for k in range(j):
                    sum1 += pow(lower[j][k], 2)
                lower[j][j] = int(math.sqrt(matrix[j][j] - sum1))
            else:
                 
            
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k])
                if(lower[j][j] > 0):
                    lower[i][j] = int((matrix[i][j] - sum1) /
                                               lower[j][j])
 

    print("Triangular\t\tTranspuesta")
    for i in range(n):
         

        for j in range(n):
            print(lower[i][j], end = "\t")
        print("", end = "\t")
         

        for j in range(n):
            print(lower[j][i], end = "\t")
        print("")

In [46]:
n = 3;
matrix = [[4, 12, -16],
          [12, 37, -43],
          [-16, -43, 98]];
Cholesky(matrix, 3)



Triangular		Transpuesta
2	0	0		2	6	-8	
6	1	0		0	1	5	
-8	5	3		0	0	3	


In [32]:
#Descomposicion LU

MAX = 100
 
 
def LU(mat, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
 
    for i in range(n):
 

        for k in range(i, n):
 
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
 
            upper[i][k] = mat[i][k] - sum
 
   
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  
            else:
 
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])
 
 
    print("Lower Triangular\t\tUpper Triangular")

    for i in range(n):
 

        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
 

        for j in range(n):
            print(upper[i][j], end="\t")
        print("")

In [33]:
mat = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]
 
LU(mat, 3)

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	


In [4]:
import math

math.pi**math.e

22.45915771836104

In [5]:
math.e**math.pi

23.140692632779263